# Generated by Django 6.0.6 on 2026-06-09 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callsign', models.CharField(max_length=20)),
                ('registration', models.CharField(max_length=20)),
                ('aircraft_type', models.CharField(default='Gulfstream G650', max_length=50)),
                ('origin_name', models.CharField(max_length=100)),
                ('destination_name', models.CharField(max_length=100)),
                ('origin_iata', models.CharField(max_length=4)),
                ('destination_iata', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('taxiing', 'Taxiing'), ('airborne', 'Airborne'), ('cruising', 'Cruising'), ('descending', 'Descending'), ('landed', 'Landed')], default='scheduled', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('altitude_ft', models.IntegerField(default=0)),
                ('speed_kts', models.IntegerField(default=0)),
                ('heading', models.FloatField(default=0.0)),
                ('simulation_speed', models.FloatField(default=1.0)),
                ('is_playing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('jet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.jet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('jet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='tracker.jet')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
